<a href="https://colab.research.google.com/github/miguelalejo/2021-Better-Working-World-Data-Challenge/blob/main/PytorchPracticeCap1_DataCamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
tensor_a = torch.rand(3,3)
tensor_a

tensor([[0.0024, 0.8762, 0.2584],
        [0.6295, 0.4686, 0.7325],
        [0.8319, 0.3865, 0.2508]])

In [3]:
tensor_a_size = tensor_a.size
tensor_a_size

<function Tensor.size>

In [4]:
tensor_a_shape = tensor_a.shape
tensor_a_shape

torch.Size([3, 3])

In [5]:
tensor_ones = torch.ones(3,3)
tensor_ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
tensor_eye = torch.eye(3)
tensor_eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [7]:
tensor_matmul = torch.matmul(tensor_ones,tensor_eye)
tensor_matmul

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
tensor_prod = tensor_ones * tensor_eye
tensor_prod

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])